//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.3615
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UBT.AI4.Bio.DivMobi.ListSynchronization.MediaServiceProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://adventure-works.com/2007/03/01", ConfigurationName="MediaServiceProxy.DiversityMediaService")]
    public interface DiversityMediaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adventure-works.com/2007/03/01/DiversityMediaService/BeginTransaction", ReplyAction="http://adventure-works.com/2007/03/01/DiversityMediaService/BeginTransactionRespo" +
            "nse")]
        string BeginTransaction(string rowGuid, string fileName, string type, float latitude, float longitude, float altitude, string author, string timestamp, int projectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adventure-works.com/2007/03/01/DiversityMediaService/EncodeFile", ReplyAction="http://adventure-works.com/2007/03/01/DiversityMediaService/EncodeFileResponse")]
        string EncodeFile(byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adventure-works.com/2007/03/01/DiversityMediaService/Commit", ReplyAction="http://adventure-works.com/2007/03/01/DiversityMediaService/CommitResponse")]
        string Commit();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adventure-works.com/2007/03/01/DiversityMediaService/Rollback", ReplyAction="http://adventure-works.com/2007/03/01/DiversityMediaService/RollbackResponse")]
        void Rollback();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adventure-works.com/2007/03/01/DiversityMediaService/Submit", ReplyAction="http://adventure-works.com/2007/03/01/DiversityMediaService/SubmitResponse")]
        string Submit(string rowGuid, string fileName, string type, float latitude, float longitude, float altitude, string author, string timestamp, int projectId, byte[] data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface DiversityMediaServiceChannel : UBT.AI4.Bio.DivMobi.ListSynchronization.MediaServiceProxy.DiversityMediaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class DiversityMediaServiceClient : System.ServiceModel.ClientBase<UBT.AI4.Bio.DivMobi.ListSynchronization.MediaServiceProxy.DiversityMediaService>, UBT.AI4.Bio.DivMobi.ListSynchronization.MediaServiceProxy.DiversityMediaService {
        
        public DiversityMediaServiceClient() {
        }
        
        public DiversityMediaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DiversityMediaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiversityMediaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiversityMediaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string BeginTransaction(string rowGuid, string fileName, string type, float latitude, float longitude, float altitude, string author, string timestamp, int projectId) {
            return base.Channel.BeginTransaction(rowGuid, fileName, type, latitude, longitude, altitude, author, timestamp, projectId);
        }
        
        public string EncodeFile(byte[] data) {
            return base.Channel.EncodeFile(data);
        }
        
        public string Commit() {
            return base.Channel.Commit();
        }
        
        public void Rollback() {
            base.Channel.Rollback();
        }
        
        public string Submit(string rowGuid, string fileName, string type, float latitude, float longitude, float altitude, string author, string timestamp, int projectId, byte[] data) {
            return base.Channel.Submit(rowGuid, fileName, type, latitude, longitude, altitude, author, timestamp, projectId, data);
        }
    }
}
